'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { Level } from '../../lib/evaluation';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts';
import { ShieldCheck, Clock3, Flame, ArrowRight, BookOpen, Sparkles, Lock, CheckCircle2 } from 'lucide-react';
const data=[{day:'Lun',score:35},{day:'Mar',score:48},{day:'Mié',score:45},{day:'Jue',score:68},{day:'Vie',score:82}];
const levels: Level[] = ['Básico', 'Intermedio', 'Avanzado'];
const modules = [
  { level: 'Básico' as const, title: 'Fundamentos y uso responsable', description: 'Comprende la IA, crea tus primeros prompts y protege la información.', lessons: ['Define una tarea concreta, proporciona contexto y solicita un formato de respuesta.', 'Evita introducir credenciales o datos confidenciales en herramientas públicas.', 'Contrasta las respuestas con fuentes fiables antes de utilizarlas.'] },
  { level: 'Intermedio' as const, title: 'IA aplicada a tu trabajo', description: 'Mejora tus instrucciones y evalúa la calidad de las respuestas.', lessons: ['Divide las tareas complejas en pasos y añade ejemplos de resultados esperados.', 'Evalúa posibles alucinaciones y sesgos con casos representativos.', 'Compara resultados usando criterios de calidad definidos antes de generar.'] },
  { level: 'Avanzado' as const, title: 'Integración y gobernanza', description: 'Explora RAG, agentes y controles para adoptar IA de forma responsable.', lessons: ['Utiliza RAG para aportar información pertinente y verifica las fuentes recuperadas.', 'Limita los permisos de los agentes y trata el contenido externo como no confiable.', 'Monitoriza el rendimiento con datos no vistos y considera el coste de los errores.'] },
];
export default function Dashboard(){
 const [userLevel, setUserLevel] = useState<Level | null>(null);
 const [loaded, setLoaded] = useState(false);
 const [storageError, setStorageError] = useState(false);
 const [activeModule, setActiveModule] = useState<Level | null>(null);
 useEffect(() => {
   function readLevel() {
     try {
       const saved = localStorage.getItem('userLevel');
       setUserLevel(levels.includes(saved as Level) ? saved as Level : null);
       setStorageError(false);
     } catch { setUserLevel(null); setStorageError(true); }
     setLoaded(true);
     setActiveModule(null);
   }
   readLevel();
   function onStorage(event: StorageEvent) {
     if (event.key === 'userLevel' || event.key === null) readLevel();
   }
   window.addEventListener('storage', onStorage);
   return () => window.removeEventListener('storage', onStorage);
 }, []);
 const levelIndex = userLevel === null ? -1 : levels.indexOf(userLevel);
 const selectedModule = modules.find(module => module.level === activeModule);
 return <main className="mx-auto max-w-7xl px-6 py-12"><div className="flex flex-wrap justify-between gap-4"><p className="text-xs tracking-widest text-slate-500">ESPACIO DE APRENDIZAJE / MI DASHBOARD</p><span className="flex items-center gap-2 rounded-full bg-emerald-50 px-4 py-2 text-xs text-emerald-700"><ShieldCheck size={14}/>Conexión Segura SSO · Demo</span></div><div className="mt-8 flex flex-wrap justify-between gap-6"><div><h1 className="text-4xl font-semibold tracking-tight">Hola, Alex<span className="text-blue-600">.</span></h1><p className="mt-3 text-slate-500">Sigue construyendo tu confianza con IA.</p></div><div className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">Nivel de Madurez en IA</p><div className="mt-3 flex items-center gap-4"><Sparkles size={18} className="text-blue-600"/><strong className="text-sm" aria-live="polite">{!loaded ? 'Cargando nivel…' : userLevel ?? 'Sin evaluar'}</strong><span aria-label={userLevel ? `Nivel ${levelIndex + 1} de 3` : 'Nivel pendiente de evaluación'} className="flex gap-1">{levels.map((level, i)=><span key={level} className={`h-2 w-4 rounded-full ${i <= levelIndex ? 'bg-blue-600' : 'bg-slate-200'}`}/>)}</span></div></div></div><p className="mt-6 text-xs text-slate-400">Perfil y métricas ilustrativos. Sin autenticación real.</p><section aria-label="Métricas" className="mt-6 grid gap-5 md:grid-cols-3"><article className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex justify-between text-sm text-slate-500">Progreso del Módulo Actual<BookOpen size={18}/></div><p className="mt-5 text-3xl font-semibold">65%</p><div role="progressbar" aria-label="Progreso del módulo" aria-valuenow={65} aria-valuemin={0} aria-valuemax={100} className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-full w-[65%] rounded-full bg-blue-600"/></div><p className="mt-3 text-xs text-slate-500">Fundamentos de IA</p></article><article className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex justify-between text-sm text-slate-500">Horas Ahorradas Estimadas<Clock3 size={18}/></div><p className="mt-5 text-3xl font-semibold">8.5 <span className="text-base font-normal">horas</span></p><p className="mt-4 text-xs text-emerald-700">+2.1 horas respecto a la semana anterior</p></article><article className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex justify-between text-sm text-slate-500">Racha de Días<Flame size={18} className="text-amber-600"/></div><p className="mt-5 text-3xl font-semibold">5 <span className="text-base font-normal">días consecutivos</span></p><p className="mt-4 text-xs text-slate-500">La constancia hace la diferencia</p></article></section><section aria-labelledby="modules-title" className="mt-10">
 <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-widest text-blue-700">TU RUTA DE APRENDIZAJE</p><h2 id="modules-title" className="mt-2 text-2xl font-semibold">Módulos de estudio</h2></div><Link href="/evaluacion" className="text-sm font-semibold text-blue-700">{userLevel ? 'Actualizar mi nivel' : 'Evaluar mi nivel'}</Link></div>
 <p className="mt-3 text-sm leading-6 text-slate-500">Avanza desde los fundamentos: domina el módulo anterior y vuelve a evaluar tus conocimientos para desbloquear el siguiente nivel.</p>
 {loaded && !userLevel && <p className="mt-4 rounded-lg border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900">{storageError ? 'No podemos leer tu nivel. Habilita el almacenamiento del navegador y completa la evaluación.' : 'Completa la evaluación inicial para conocer tu nivel y habilitar tus módulos.'}</p>}
 <div className="mt-6 grid gap-5 md:grid-cols-3">{modules.map((module, index) => {
   const locked = index > levelIndex;
   return <article key={module.level} aria-label={`Módulo ${module.level}`} className={`flex flex-col rounded-xl border border-slate-200 bg-white p-6 ${locked ? 'opacity-50 cursor-not-allowed' : ''}`}>
     <div className="flex items-center justify-between"><span className="rounded-lg bg-blue-50 p-3 text-blue-700">{locked ? <Lock aria-label="Bloqueado" size={22}/> : <BookOpen size={22}/>}</span><span className="text-xs font-medium text-slate-500">{locked ? 'Bloqueado' : 'Disponible'}</span></div>
     <h3 className="mt-5 text-xl font-semibold">{module.level}</h3><p className="mt-2 text-sm font-medium">{module.title}</p><p className="mt-3 text-sm leading-6 text-slate-500">{module.description}</p>
     <p className="mb-5 mt-5 text-xs leading-5 text-slate-500">{locked ? (!userLevel ? 'Requiere evaluación inicial.' : `Supera el módulo ${levels[index - 1]} y acredita el nivel ${module.level} en la evaluación.`) : 'Acceso habilitado por tu nivel de evaluación.'}</p>
     <button disabled={locked} onClick={() => setActiveModule(module.level)} className="mt-auto flex items-center justify-between gap-2 rounded-lg bg-blue-950 px-4 py-3 text-sm font-semibold text-white hover:bg-blue-900 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-600">{locked ? 'Módulo bloqueado' : 'Abrir módulo'}{locked ? <Lock size={16}/> : <ArrowRight size={16}/>}</button>
   </article>;
 })}</div>
 {selectedModule && <section aria-labelledby="active-module-title" className="mt-6 rounded-xl border border-blue-100 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h3 id="active-module-title" className="text-lg font-semibold">{selectedModule.level}: {selectedModule.title}</h3><button onClick={() => setActiveModule(null)} className="text-sm text-slate-500">Cerrar módulo</button></div><p className="mt-2 text-xs text-slate-500">Guía introductoria · La lectura no modifica tu nivel de evaluación.</p><ul className="mt-5 space-y-4">{selectedModule.lessons.map(lesson=><li key={lesson} className="flex gap-3 text-sm leading-6 text-slate-600"><CheckCircle2 size={18} className="mt-1 shrink-0 text-blue-600"/>{lesson}</li>)}</ul><Link href="/evaluacion" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-blue-700">Evaluar mis conocimientos<ArrowRight size={16}/></Link></section>}
 </section><div className="mt-6 grid gap-6 lg:grid-cols-[2fr_1fr]"><section className="min-w-0 rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Tu evolución en IA</h2><p className="mt-1 text-sm text-slate-500">Rendimiento en los últimos 5 días</p><div className="mt-8 h-72" role="img" aria-label="Puntajes: lunes 35, martes 48, miércoles 45, jueves 68 y viernes 82 sobre 100"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{right:15,left:-15}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis domain={[0,100]} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[`${v}/100`,'Rendimiento']}/><Line type="monotone" dataKey="score" stroke="#2563eb" strokeWidth={3} dot={{r:4}}/></LineChart></ResponsiveContainer></div></section><aside className="rounded-xl bg-blue-950 p-8 text-white"><Sparkles className="text-blue-300" size={28}/><p className="mt-7 text-xs tracking-widest text-blue-300">TU SIGUIENTE PASO</p><h2 className="mt-3 text-2xl font-semibold">Conoce tu punto de partida.</h2><p className="mt-4 text-sm leading-7 text-slate-300">Completa una evaluación breve y descubre qué conceptos puedes reforzar.</p><p className="mt-5 text-xs text-blue-200">15 preguntas · A tu ritmo</p><Link href="/evaluacion" className="mt-8 flex items-center justify-between rounded-lg bg-white p-4 text-sm font-semibold text-blue-950">Iniciar evaluación<ArrowRight size={17}/></Link></aside></div></main>}
